### ISSUE TITLE
Hmmm, New/Old? Changes in the BRA file format

### ISSUE THREAD

**Issue by marcussacana** [Sewer56/Xanadu-BRA-Decompress#2]
I found other game that are using the BRA file format,
The "Fairy Fencer F: Advent Dark Force" [Steam] 

Some .BRA archives are extracted without problem, but I certain ones the file name is extracted wrong... Well, nothing soo wrong, I take a look in the .bra archive, and take a look:
![Captura de tela de 2020-09-17 20-14-30](https://user-images.githubusercontent.com/10576957/93537678-97404f80-f922-11ea-86bc-5d7d52b56b4a.png)
For some reason looks like the name isn't null-terminated... Or not: 
![Captura de tela de 2020-09-17 20-17-40](https://user-images.githubusercontent.com/10576957/93537785-de2e4500-f922-11ea-93c7-f304eddcbf85.png)
Anyway, looks like this is something random, you who already know about this file format have any idea?
Maybe there are any other place with the real file name length? or this is just someting to make hard extract...?

**Comment by Sewer56** [comment]
Sorry for taking this long to respond; I ended up slightly forgetting about it.
Had a quick dig up some of my old files.

These are my notes on the format from around the time I quickly hacked this tool up:
```csharp
// File Header Section (0x10)
string headerTag; // Constant: PDA (Null Terminated)
uint32 compressionType; // Presumed to be this. Value is constant 2
uint32 fileEntryOffset; // Offset relative to start of file to the end of compressed file data after the header.
uint32 fileCount; // File count
    
// Raw Data Section (Variable Length), Files consist of a 0x10 header & raw compressed data.
uint32 uncompressedSize; // Size expected after decompression.
uint32 compressedSize; // Size of compressed data after this header.
byte[8] unknown; // Sometimes 0, not a pointer/offset.
byte[x] compressedData; // Raw compressed data. Compression type is deflate. (Might be deflate64, I didn't verify, works under both).

// File entry section (immediately succeeding compressed data), variable length, repeated fileCount times.. 
time_t archiveTime; // C Time format. Appears to be the time the file was last packed/modified in the archive. Archive appears to be one of type that is built from scratch but files are simply updated and pushed in, potential for lots of unused goodies.
uint32 unknown; // The purpose is unknown.
uint32 compressedSize; // Same as in the file entry, except including 0x10 header.
uint32 uncompressedSize; // Same as in file entry, size post decompression.
uint16 fileNameLength; // Length of file name, including junk terminators.
uint16 fileFlags; // ? Seem to be flags, cannot tell as of yet, proper investigation was not made.
uint32 fileOffset; // Offset to the Raw Data Section for this file, relative to start of file.
string fileName; // Name of the file, lesser or equal to the fileNameLength field.
byte[1-3] shitPadding; // Literally what the name implies and the awful part of this format. Rather than null terminating strings and having the length correctly explicitly defined, the format pads the end of the file name with random junk data (which changes every time file name length changes) until the combined length of both the name and the junk is integer divisible by 4.
```

Quite honestly; string termination in this format was always very weird. The ending of most strings were padded with non-ASCII characters. The actual encoding itself is probably ANSI/Windows-1252 in all honesty, but the real problem here I think is no clear indicator of where the actual string actually ends and the length of the padding is variable.

Back then, I simply did a quick hackjob by removing all characters that are invalid in file paths and then trimming the string based on extension. I was very, very lazy and did it in a flawed way that assumed 3 character extensions, which is [really, really bad programming!!](https://github.com/Sewer56/Xanadu-BRA-Decompress/blob/7576ac442db97f51dd55852418213cd8e02dda09/Xanadu-BRA-Decomrpess/Program.cs#L145). A better "guess" would be to find the last index of the extension marker `.` and advance to first non-ASCII character, just a few lines of code.

In truth, the best way is to probably reverse game code to get to the bottom of this; shouldn't be that hard, it's just that I don't have a good reason to.

I really ought to clean this tool up a bit; I think I hacked this all together in the span of 2-6 hours for one time use only, hence the current state. It's just that I have so many repos to do things on, including some bigger projects that a lot of the old stuff gets left behind. I wish that were not the case but there's only one of me.

**Comment by marcussacana** [comment]
well, we have few 4-char extensions, like the .gbin and .gstr in this case, well, I will take a look here thx
